#+LANGUAGE: de
#+OPTIONS: toc:nil  broken-links:mark

#+begin_export html
---
layout: post.liquid
title:  "Konfuzius: erst handeln, dann reden"
date: 2023-07-11 21:55
last_updated: 2023-07-11 21:55
tags:
  - deutsch
  - tagebuch
  - konfuzius
  - handeln
  - überprüfen
categories: [deutsch, tagebuch]
permalink: /2023-07-11-konfuzius-handeln
toc: false
---

> Dieser Eintrag ist Teil meines Ziels: [Mein Deutsch verbessern](/now)
#+end_export


* Konfuzius: erst handeln, dann reden
  
  Ich höre gerade ein Hörbuch über Konfuzius: Gespräche des
  Konfuzius.

  Der Buch ist eine Liste von Sprüche zugeschriben zu Konfuzius. Die
  Originale Texte war auf Chineschish geschrieben. Konfuzius hat das
  Buch nicht geschrieben, seine Schüler haben es getan.

  Auch wenn die Texte ist gut ubersetz, ist das Buch schwer zu
  verstehen. Man muss  die Bedeutung jede Sprüche interpretieren.

  Ich höre das Buch auf Englisch und in diese Übersetzung gibt es
  die folgende Sprüche: 

  #+begin_quote
  The superior man acts before he speaks, and afterwards speaks
  according to his action.
  -- [[https://www.brainyquote.com/quotes/confucius_385565][brainyquote.com]] 
  #+end_quote

  Für die aktuellen Beitrag habe ich eine Deutsche Übersetzung für die
  Sprüche gesucht und ich habe ein paar gefunden:
  
  #+begin_quote
  1. Erst handeln und dann mit seinen Worten sich danach richten. 
     -- [[https://www.aphorismen.de/zitat/4075][aphorismen.de]] 

  2. Erst handelt er, wie er denkt. Dann spricht er, wie er handelt.
     -- [[https://www.zitat-des-tages.de/zitate/erst-handelt-er-wie-er-denkt-dann-spricht-er-wie-er-handelt-konfuzius][zitat-des-tages.de]]

  3. Zi-gong fragte, was einen Edlen ausmache.
     Der Meister antwortete: »Erst handelt er, wie er
     denkt. Dann spricht er, wie er handelt.«
     -- [[https://www.reclam.de/data/media/978-3-15-011110-9.pdf][übersetzt und herausgegeben von Ralf Moritz]]
  #+end_quote


  Der Referenz zu ein /superior man/ habe ich gewundert, also ich habe
  auch eine Spanische Übersetzung gesucht:
  
  #+begin_quote
  El hombre superior actúa antes de hablar, y después habla de acuerdo
  a sus acciones. -- [[https://www.elciudadano.com/educacion/quien-fue-confucio-conocelo-por-su-pensamiento/09/28/][elciudadano.com]]
  #+end_quote


  Alle Deutsche ubersetzungen nehmen keine Bezug auf einen höheren
  Menschen. Die 3. Zitat spricht über /Edlen/, und das hat
  verschiedene Bedeutungen/Übersetzungen:

  1. von hochwertige Qualität
  2. English: nobel


** Edel (君子): der moralisch ideale Mensch

   Edel ist die Übersetzung von das Chinesisches Wort: 君子 (junzi):
   
   #+begin_quote
   junzi; man of virtue; high-minded person; noble person; superior
   person
   -- [[https://en.wiktionary.org/wiki/%E5%90%9B%E5%AD%90][wiktionary.org]]
   #+end_quote
