#+LANGUAGE: de
#+OPTIONS: toc:nil  broken-links:mark

#+begin_export html
---
layout: post.liquid
title:  "To-do Listen mit Org mode für Emacs"
date: 2023-05-14 21:35
last_updated: 2023-05-14 21:36
tags: deutsch tagebuch org-mode emacs todo ueberpruefen
categories: [deutsch, tagebuch, emacs, org-mode, todo]
permalink: /2023-05-14-todos-org-mode
toc: false
---
> Dieser Eintrag ist Teil meines Ziels: [Mein Deutsch verbessern](/now) 
#+end_export


* To-do Listen mit Org mode für Emacs
  
  Seit vielen Jahren bin ich ein Fan von to-do Listen. Ich habe viele
  unterschiedlichen varianten probiert, z.B., plain-text Files, Trello
  Boards, Atlassian JIRA, Google Wave und andere.

  Oft muss ich ein neues Tool finden und alle meine to-dos migrieren
  und das finde ich so unangenehm und langweilig. Manchmal ist der
  grund Kuriosität, ich möchte einfach neue Features, wie Farbige
  Notizen, oder meine to-dos visuel zu manipulieren, manchmal möchte
  ich eine neue Methode meine notizen zu organisieren, ich habe immer
  ein guter Grund.

  In das letzte Jahr oder so bin ich zu faul und müde geworden und
  möchte jetzt etwas die einfach funktioniert, dass schnell zu
  bearbeiten ist und das flexible ist. Ich glaube, ich habe etwas mit
  diesem eingenschaften gefunden, Org mode for Emacs.

  Org mode for Emacs ist ein plug-in für das Text-Editor Emacs und ich
  habe es langsam und schrittweise adoptiert für alle meine neue to-do
  Listen. Man muss viele neue Konzepte lernen, nicht nur über Org
  mode, aber auch über der Emacs Text-Editor, es ist eine sehr
  flexible un anpassbare Program, dass man kann Stundenlanges
  herumspielen mit all den Optionen.

