@startuml

title Building an infrastructure

'left to right direction
skinparam defaultTextAlignment center

card "All changes \nare code" as code
card "Avoid ad-hoc\nchanges" as adhoc
card "Building Infrastructure is \na Development Process" as dev
card "Cattle, not pets" as cattle
note right: Components are\ngeneric/replaceable
card "Cost" as cost
card "Disaster\nRecovery" as dr
card "Gold server" <<Artefacts repository>> as artefacts
card "Golden server" <<Template>> as golden
card "Labor" as labor
card "Pull is better\nthan Push" as pull
note right: Servers are passive.\nClients initiate \ninteractions
card "Repeatability" as repeat
card "Version \nControl" as vc
note right: Traces the evolution\n of the infrastructure


artefacts --> golden: serves
adhoc --> cattle: produces
adhoc --> code: means
cattle --> dr: improves
dr --> cost: reduces
dev --> vc: requires
golden --> repeat: enables
labor --> cost: reduces
pull --> artefacts: requires
repeat --> labor: reduces
vc --> code: needs

@enduml
