@startuml

title Principles for building infrastructures

left to right direction
skinparam defaultTextAlignment center

frame "Economic principles" as econ {
	card "Cost \nEfficiency" as cost
}

frame "Operational principles" {
	card "Evolvability" as evol
	card "Autonomy" as autonomy
	note bottom: Clients responsible\nto remain compliant
}


frame "Automation" as auto {
	card "Repeatability" as repeat
	card "Immutable \ninfrastructure" as ii
	card "Cattle, not pets" as cattle
}

card "Pull-based" as pull
note bottom: Clients initiate \nall interactions

frame "Infrastructure as Code" as iac {
	card "Version \nControl" as vc
	card "All changes \nare code" as acac
	card "Re-usability" as reuse
}

card "Gold server" <<Artefacts repository>> as artefacts

cost --> reuse
evol --> iac
acac --> auto
autonomy --> pull
reuse --> artefacts

@enduml
