#+LANGUAGE: en
#+OPTIONS: toc:nil  broken-links:mark

#+begin_export html
---
layout: post.liquid
title:  "AI Career"
date: 2024-10-02
last_updated: 2024-10-02
tags:
  - journal
categories: [journal]
permalink: /2024-10-02-ai-career
toc: false
---

#+end_export


At the end of 2022, after 14 years as a software engineer working in
mercenary mode I was ready for a change ...

#+begin_export html
{% include amzn_affiliate_disclaimer.html %}
#+end_export


* Act I

  Working as a software engineer can be stressful. The pace of
  modern/agile software teams is fast, bi-weekly sprints, continuous
  delivery, you build it ... you run it, etc.. On top of that, having
  to learning next programming tool/technique is very demanding.

  I have always been more of a thinker than a tinkerer; I like to look
  at topic from different angles, do some research, try a few
  things, step back and switch to something else while I let my
  unconscious process what I've learned, this personality was not
  compatible with my job.

  During my vacation around the end of 2021 I was going over my life
  choices and career prospects, most of my career I had jumped to the
  next role as soon as I found something that was attractive enough. I
  was now ready to commit to a long-term project/role but first I
  needed to do some research to understand my options and compare them
  somehow.
  
  
* Act II

  I would summarize my career as writing network clients for the first
  half and then writing application servers and release automation for
  the other half. In a sense I felt that I had been doing the same
  over and over for the past 10 years, only with different
  technologies. I needed a change, something more compatible
  with my personality and preferences.

  I didn't feel that I could make a drastic change like going out of
  the software world. Writing software is the only thing I had more
  than 10 years of practical experience with and where some might even
  consider me an expert. I am not a big risk taker so I only
  considered alternative paths that could benefit from my professional
  background.

  I had been thinking about switching roles for a while and there were
  two main topics that invaded my thoughts on a regular basis:
  infrastructure automation and artificial intelligence.
  
  In recent software projects, I would spend a lot of my time
  thinking on how to improve the state of our delivery
  infrastructure. At points I would use half of my time on a project
  working on infrastructure automation tasks and was scolded for
  working on non value added tasks.

  This was very sad to experience because not attending to those tasks
  was one of the top reasons deliveries were unreliable and slow. To
  me it was like apartment mates living together and complaining that
  the apartment stinks but no one has any time to take the garbage
  out.

  AI/ML was attractive to me both because it constantly generated
  headlines, and aligns well with personal interest in the automation
  of knowledge organization and discovery.  It was also a change that
  would allow me to bring some of my transferable skills and not start
  from scratch.

  During my research, there were two main resources that I relied upon
  to Learn about what AI projects might look like in the industry:

  1. @@html:<a href="/tag/chollet.html">Chollet</a>@@'s book:
     @@html:<a href="https://amzn.to/3BsKjwK" target="_blank"> Deep
     Learning with Python.  </a>@@ the Universal Machine Learning
     workflow was exactly what I was looking for at the time, a
     high-level overview of the life cycle of an ML Project

  2. Andrew Ng's AI [[https://www.deeplearning.ai/][deeplearning.ai]]: he breaks down the different
     roles required to run successful AI projects in the enterprise
     world. His site also has tools to asses your readiness for a
     given role


  I found both resources above useful, and at the same time I was
  disheartened to learn that machine learning projects look almost the
  same as software projects.
  
  Data scientist, machine learning engineers, and other people with
  specialized skills for ML projects typically lack the practical
  experience in delivering reliable systems to production
  environments. To me that meant that were I to join such projects, I
  would end up exactly in the same role that I was trying to escape.
  
  I started to de-prioritize learning more about Machine Learning in
  the industry and decided to learn more about infrastructure.
  
  
* Act III

  During my vacation I made the resolution to double down and continue
  working as a software engineer and become even more proficient
  writing code for applications and release automation.
  
  My resolution lasted less than 4 hours after my return to work. On
  my first day after vacation, all it took was to read my mailbox and
  chat messages to remind me why I was considering a change in the
  first place: broken pipelines, a long queue of pull requests on
  which most feedback is brushed off as nitpicking, pull requests that
  are 2000 LOC long, non-stop merging to the mainline even after it
  has been broken for 2 weeks, team retrospectives that do not produce
  any value, aggressive deadlines but no compromises on scope, the
  need to reinvent the wheel on every small module just because
  developers are not familiar enough with the programming framework we
  use and them not feeling like they can invest any time toe learn on
  the job since they have a tight deadlines, the constant churn of
  external consultants that need to be onboarded and that only makes
  late projects even later, etc, etc, etc.

  I started looking for a change on the same day and that would lead
  me into the world of IT infrastructure architecture.

  The company is large and more than 100 years old, it has deployed
  pretty much any technology worth mentioning in the last 50 years. My
  IT universe expanded from delivery pipelines, and infrastructure
  automation to anything from robots used in logistics warehouses,
  temperature control systems, HR systems, telephony/fax/printing
  hardware, and all other kinds of IT related projects, of which I
  would have never known.

  Before my role as infrastructure architect, I already thought that
  infrastructure was a huge domain, but I could still see the edges of
  my IT universe. It's 2024, two years on the new role I can say that
  I have never felt that way again; the IT universe keeps expanding,
  and its boundaries are unknown to me.

  After a couple of years of switching to focus on IT infrastructure
  architecture, I'm out of it again, now focusing on learning more
  about cloud architecture a small subset of IT infrastructure, maybe
  this time it will last longer, let's just hope that Cloud is not
  just another fad.


* Finding your own path
  
  Over the past few years I have met with colleagues and friends who
  are at stage on their careers, where they are not sure whether they
  want to continue on the current path or take a different one. Many
  of them, like me find the field of artificial intelligence, very
  attractive, but they also haven't had any practical experience
  machine learning engineer any project. So if you are considering
  such a move, I can highly recommend Chollet's book. It's a window
  into the world of machine learning engineering in the industry,
  directly from an influential software engineer and AI researcher.



* TODO Story structure checklist: [[https://chatgpt.com/share/66fea7f2-cdf4-800f-ada1-cc9b8a748c57][chat]]                             :noexport:
  
* COMMENT Local variables

  Taken from: 
  https://emacs.stackexchange.com/a/76549/11978
  
  # Local Variables:
  # org-md-toplevel-hlevel: 2
  # End:
  


