#+LANGUAGE: en

#+begin_comment
1) =toc:nil=: Do not generate Org TOC:
   https://orgmode.org/manual/Table-of-Contents.html
2) =broken-links=: Continue export even when there are broken links 
   https://orgmode.org/manual/Export-Settings.html
#+end_comment
#+OPTIONS: toc:nil  broken-links:mark

#+begin_comment
Jekyll front matter:
https://jekyllrb.com/docs/front-matter/
#+end_comment
#+begin_export html
---
layout: post.liquid
title:  "Salsa practice ideas"
date: 2025-05-03
last_updated: 2025-05-03
tags:
  - salsa
  - dancing
categories: [salsa, dancing]
permalink: /2025-05-03-salsa-practice
toc: true
---

#+end_export

Here are some ideas for salsa dance practice, the main goals are to
train the ability to place the pause at different times deliberately. 

During the COVID pandemic I started to get bored of practicing only
the On 1 basic step for inline Salsa. I was trying to come up with
some ideas to spice up my practice sessions and also understand more
about the different ways of dancing inline Salsa.

One of the key concepts in Salsa is the pause. My goal was to
see how placing the pause in different beats changes the feel of
the dance. 

  
* The Basic step On 1
  :PROPERTIES:
  :CUSTOM_ID: basic-on1
  :END:

  For the Basic steps On 1, start by taking a step forward with the
  left foot and stepping with the ball of your foot on beat 1 and the
  pause comes in beats 4 and 8. 
  
  #+begin_export html
  <div style="text-align: center">
    <a href="assets/svg/salsa-on1-basic.svg">
      <img src="assets/svg/salsa-on1-basic-pause-on-4-8.svg"
           alt="On 1 Basic step">
    </a>
  </div>
  #+end_export


** Diagram notes
   :PROPERTIES:
   :CUSTOM_ID: basic-on1-diagram-notes
   :END:

   1. *the beat*: the first row shows the beat, in Salsa music there are
      2 sets of 4 beats, 8 in total
   2. *home position*: the beat 0 shows the initial position, some
      people also call this the home position
   3. *transfer of weight*: the red color in the steps indicates where
      your body weight is supposed to be
   4. only the *ball of your feet* touch the ground: the footprints
      without the heel mean that you are only stepping with the ball
      of your feet
   5. *traveling foot*: an arrow instead of a step shows the direction
      your foot is traveling and not touching the ground
   6. *step on the beat*: the X in the last row mean that foot touches
      the ground on that beat
   7. *pause*: the Ps in the last row tell you where the pause is




* Changing the timing of the Pause
  :PROPERTIES:
  :CUSTOM_ID: placing-the-pause
  :END:
  :LOGBOOK:
  - CLOSING NOTE [2025-05-08 Do 23:27]
  :END:

  For reference, in the On 1 Basic, the pause is on beats 4 and 8. The
  goal is now to place the Pause in different beats, e.g., 1+5, 2+6,
  or 3+7. 

  I the following sections I will make the case that placing the
  pauses on different beats allows you to get a better feel of
  different instrumental rythms; for that I will be using the song
  @@html:<a href="https://www.youtube.com/watch?v=Nd78Pt6nWb8" target="_blank">@@
  Ay Mi Maria by Bloque53
  @@html:</a>@@
  as reference for the Tumba, Bass and Piano rythms.
  
  
** Pause on beats 1 and 5: feel the Tumbao
   :PROPERTIES:
   :CUSTOM_ID: pause-on-1+5
   :END:

   #+begin_export html
   <div style="text-align: center">
     <a href="assets/svg/salsa-on1-basic.svg">
       <img src="assets/svg/salsa-on1-basic-pause-on-1-5.svg"
            alt="On 1 Basic step">
     </a>
   </div>
   #+end_export

   When dancing in this style, the forward and backward motions align
   well with the TUM TUM of the simple Tumba rythm.
   

** Pause on beats 2 and 6: feel the Bass
   :PROPERTIES:
   :CUSTOM_ID: pause-on-2+6
   :END:

   #+begin_export html
   <div style="text-align: center">
     <a href="assets/svg/salsa-on1-basic.svg">
       <img src="assets/svg/salsa-on1-basic-pause-on-2-6.svg"
            alt="On 1 Basic step">
     </a>
   </div>
   #+end_export

   You can hear the /doom/ of the base on beats 1, 3, 5 and 7. When I
   practice this style I imagine that I'm dancing on the fret of the
   Bass; when the pause on beat 2/6 comes, it feels like it's me
   sutaining the Bass /doom/.


** Pause on beats 3 and 7: feel the slap
   :PROPERTIES:
   :CUSTOM_ID: pause-on-3+7
   :END:

   #+begin_export html
   <div style="text-align: center">
     <a href="assets/svg/salsa-on1-basic.svg">
       <img src="assets/svg/salsa-on1-basic-pause-on-3-7.svg"
            alt="On 1 Basic step">
     </a>
   </div>
   #+end_export

   When dancing this variation, it feels like I need to emphasize the
   Tumba slap (the PA on TUM TUM PA) on beats 2 and 6.
   

* Other ways to change the location of the Pause
  :PROPERTIES:
  :CUSTOM_ID: other-variations
  :END:

  1. you can use the same ideas of placing the pause on different
     beats when dancing On 2 and try to feel which instrument is
     emphasized for each given variation
  2. two more ways to change the location of the pause is to step on
     the Clave beats; for this I typcally need additional
     technological aids to be able to hear the Clave, more info in
     [[#practice-tools][Practice, practice, practice]]


* TODO Dancing on the Clave beats
  :PROPERTIES:
  :CUSTOM_ID: clave-beats
  :END:

** TODO Clave 2-3: Steps diagram
   :PROPERTIES:
   :CUSTOM_ID: clave-2-3
   :END:


** TODO Clave 3-2: Steps diagram
   :PROPERTIES:
   :CUSTOM_ID: clave-3-2
   :END:

   
* Practice, practice, practice
  :PROPERTIES:
  :CUSTOM_ID: practice-tools
  :ID:       A5AD808A-74DB-407B-A0DD-979630C7ECC6
  :END:
  
  You will need some good tunes to practice, I suggest you use music that is
  not too fast and song on which the the piano, bass, and Tumba rythms
  are easy to hear. I like to use Ay Mi Maria! by Bloque53.

  #+begin_export html
  <div style="text-align: center">
    <iframe width="560" height="315"
            src="https://www.youtube.com/embed/Nd78Pt6nWb8?si=q80DPZhByyAnjyhv"
            title="YouTube video player"
            frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            referrerpolicy="strict-origin-when-cross-origin"
            allowfullscreen></iframe>
  </div>
  #+end_export


  For the Clave rythm I like to use an app like [[https://apps.apple.com/de/app/salsa-rhythm/id379868541][Salsa Rythm]] or [[https://salsabeatmachine.org][The
  Salsa Beat Machine]], you can control the speed and volume of each
  instrument! That has helped me a lot connect each timing of the
  pause to different instruments. 
  

* Conclusion
  :PROPERTIES:
  :CUSTOM_ID: conclusion
  :END:

  Now you have 6 ways to practice placing the pause:
  
  1) 4 positions of the pause on the basic and
  2) 2 positions when dancing on the clave beats (clave 2-3 and 3-2)






* References
  :PROPERTIES:
  :CUSTOM_ID: refs
  :END:

  1. The step icons were taken from [[https://www.onlinewebfonts.com/icon][svg icons]] and are licensed by CC
     BY 4.0 


  
* COMMENT Local variables
  
  Taken from: 
  https://emacs.stackexchange.com/a/76549/11978
  
# Local Variables:
# org-md-toplevel-hlevel: 2
# End:
  
