#+LANGUAGE: de
#+OPTIONS: toc:nil num:nil  broken-links:mark

#+begin_export html
---
layout: post.liquid
title:  "Wer zuerst kommt, malt zuerst!"
date: 2023-05-10 21:03
last_updated: 2023-06-23 22:05
tags: deutsch journal redewendung priorisierung
permalink: /2023-05-10-wer-zuerst-kommt
categories: [deutsch, journal]
toc: false
---
#+end_export


Hier ist noch ein Eintrag, um mein Deutsch zu üben. So weit gibt es
kein Thema. Deshalb schreibe ich einfach meine Gedanken auf.

Ich habe eine neue Redewendung gelernt: Wer zuerst kommt, malt
zuerst!

Wenn ich zu viel zu tun habe, und andere Menschen auf mich warten,
dann kann ich diese Redewendung anwenden und meine Aufgaben in
derselben Reihenfolge erledigen, wie ich sie bekommen habe.

Natürlich gibt es Ausnahmen, weil es bestimmte Aufgaben gibt, die
wichtiger sind als andere. Manchmal ist es einfach zu entscheiden
welche Aufgabe wichtiger ist, aber manchmal nicht. In diesem Fall
muss ich mit meinen Kollegen zusammen arbeiten, um eine sinnvolle
Priorität für jede Aufgabe zu setzen.

Je mehr Aufgaben, desto wichtiger die Priorisierung. Manchmal ist es
möglich mehrere Aufgaben parallel auszuführen. Man muss auf jeden
Fall die Aufgaben analysieren und entscheiden, ob sie voneinander
unabhängig sind.

