#+LANGUAGE: de
#+OPTIONS: toc:nil num:nil  broken-links:mark

#+begin_export html
---
layout: post.liquid
title:  "Der Code des Kapitals"
date: 2023-09-11 20:18
last_updated: 2023-09-11 20:18
tags:
  - deutsch
  - journal
  - überprüfen
categories: [deutsch, journal]
permalink: /2023-09-11-code-des-kapitals
toc: false
---

#+end_export


Ich höre gerade /[[https://www.audible.com/pd/The-Code-of-Capital-Audiobook/1541431898][The Code of Capital]]/ von Katharina Pistor. Das Buch
handelt davon, wie Menschen das Gesetz nutzen, um viele Dinge als
Kapital zu codieren.

#+begin_export html
{% include amzn_affiliate_disclaimer.html %}
#+end_export


Die rechtlichen Module wurden über Jahrzehnte entwickelt und immer
weiter verbessert. Diese Module sind immer dann präsent, wenn neue
Kategorien von Vermögenswerten erfunden werden.

Nach einer Erfindung haben die Erfinder eine große Motivation, ihre
Erfindung vor anderen zu schützen und dann die Gewinne zu
realisieren.

Ursprünglich war Land das Hauptvermögen, das jemand als Kapital
codieren konnte. Vieles hat sich verändert, und heutzutage kann man
auch Ideen, Methoden und andere abstrakte Konzepte als Kapital
codieren.

Früher konnte man Zäune um das Land bauen und andere
aussperren. Heute kann man dasselbe mit Ideen tun, zum Beispiel mit
Patenten. Die Patentinhaber können andere Menschen aussperren und
die Vorteile ihrer Idee allein genießen.

@@html:<a href="https://amzn.to/4eKrSC9"
          target="_blank">
        Kaufe das Buch bei Amazon.
       </a>@@
@@html:<a href="https://amzn.to/3N4MdGr"
          target="_blank">
         Auch als Hörbuch erhältlich.
       </a>@@



