#+LANGUAGE: de
#+OPTIONS: toc:nil  broken-links:mark

#+begin_export html
---
layout: post.liquid
title:  "Der Anschein von Fairness"
date: 2024-02-11 So 11:19]
last_updated: 2024-02-11 So 11:19
tags:
  - journal
  - deutsch
  - überprüfen
categories: [deutsch, journal]
#permalink: /YYYY-mm-dd-title
toc: false
---
#+end_export


Ich höre gerade das Hörbuch von Richard Thaler, Misbehaving
(Fehlverhalten). Im Kapitel 14: "What seems fair" (Was scheint Fair)
beschreibt der Autor einige Situationen wo eine Firma hat eine
Entscheidung darüber, wie Preise festgelegt werden sollen und wie die
Kunden reagiert haben.

Das erste Beispiel bezieht sich auf Preise von Schnee schaufeln nach
einem schweren Schneefall. Die Firma hat sich entschieden die Preise
zu erhöhen, der Grund was dass mit höhere Nachfrage werden die
Schaufeln knapp und ist es Allgemeinwissen dass Preise steigern wenn
Nachfrage ist hoch und Angebote niedrig ist.

Die wiederkehrende Bemerkung im gesamtem Buch ist, das wenn Menschen
als rationale Agenten (Econs) betrachten werden, dann kann man Fehler
in gesunden Menschenverstand machen, z.B., dass die durchschnittliche
Mensch würde die Entscheidung der Firma im obige Beispiel als
ungerecht beurteilen. 


* COMMENT Local variables

  Taken from: 
  https://emacs.stackexchange.com/a/76549/11978
  
  # Local Variables:
  # org-md-toplevel-hlevel: 2
  # End:
  





