#+LANGUAGE: de
#+OPTIONS: toc:nil  broken-links:mark

#+begin_export html
---
layout: post.liquid
title:  "Vorherbestimmt von Robert Sapolsky"
date: 2024-04-24 Do 18:20
last_updated: 2024-04-24 Do 18:20
tags:
  - buch
  - sapolsky
  - free-will
  - bio
  - journal
  - deutsch
  - überprüfen
categories: [deutsch, journal]
permalink: /2024-04-24-sapolsky-vorherbestimmt
toc: false
---
#+end_export

"Vorherbestimmt" ist ein Buch von Robert Sapolsky in dem, der Author
für den Determinismus argumentiert.

Sapolky erklärt, dass Freie Wille bedeutet nicht nur das man seine
eigenen Handlungen, sondern auch seine eigene Absicht wählen kann.

Eine der bekantesten Experimente zu tun mit Freie Wille, nämlich die
Libet Experimente zeigt das man Handelt, bevor man sich seine eigenen
Handlungen bewusst ist. 


*TODO: Video von Libet Experimente*

  
In der Libet Experiment werden nur die kurze Momente vor die
Handlungen analysiert, was Sapolsky asl unzureichend empfindet.  Laut
Sapolskys Definition von Freie Wille können wir die entfernte Ursache
des Verhaltens nicht ignorieren. Das bedeutet, wir müssen nicht nur
die Millisekunden, Minuten, Stunde vor analysieren sondern auch die
vorheriger Jahre, Jahrzehnte, Jahrhundert, usw. Um etwas als Freiwes
Will zu bezeichnen müssen wir die Unveruhrsachte Uhrsache finden.

Nur der unmittelbare Vergangenheit von Handlungen Betracht zu ziehen
ist wie nur die letzte 3 Minute eines Films zu schauen denkt
Sapolsky. Freie Wille Die Annerkennung für seine Handlungen geben ist
ein Eingeständniss, die Uhrsachen nicht zu kennen.


* COMMENT Local variables

  Taken from: 
  https://emacs.stackexchange.com/a/76549/11978
  
  # Local Variables:
  # org-md-toplevel-hlevel: 2
  # End:
  





