@startuml

title Building an infrastructure

'left to right direction
skinparam defaultTextAlignment center
'skinparam linetype polyline

card "All changes \nare code" as code
note left: Infrastructure as Code
card "Avoid ad-hoc\nchanges" as adhoc
card "Autonomy" as autonomy
card "Building Infrastructure is \na Development Process" as dev
card "Generic\nComponents" as generic
note right: Cattle, not pets!
card "Cost" as cost
card "Disaster\nRecovery" as dr
card "Gold server" <<Artefacts repository>> as artefacts
card "Golden server" <<Template>> as golden
card "Labor" as labor
card "Pull\ninstead of\n Push" as pull
note right: Servers are passive.\nClients initiate \ninteractions
card "Repeatability" as repeat
card "Version \nControl" as vc
note left: Traces the evolution\n of the infrastructure


artefacts --> golden: serves
adhoc --> generic: produces
adhoc --> code: means
generic --> dr: improves
dr --> cost: reduces
dev --> vc: requires
golden --> repeat: enables
labor --> cost: reduces
autonomy --> pull: means
pull --> artefacts: requires
repeat --> labor: reduces
vc --> code: needs

@enduml
