#+LANGUAGE: en
#+OPTIONS: toc:nil  broken-links:mark

#+begin_export html
---
layout: post.liquid
title:  "On intelligence"
date: 2024-10-22
last_updated: 2024-10-22
tags:
  - journal
  - ai
  - intelligence
categories: [journal, ai]
permalink: /2024-10-22-on-intelligence
toc: false
---

#+end_export


When thinking about the definition of intelligence, a recurring
question I ask myself is where is the intelligence located?


One aspect that continues to bother me is how different are the
meanings of the term intelligence depending on the context, for
example, one of the facts about human intelligence as measured by
their IQ is that it is relatively stable over the lifetime of a
person.

When readings about how intelligent (as measured by
tasks-specific benchmarks) a new AI architecture is is common to
assume that the same architecture can be made more performant by
simply training it with larger data sets. This is a strange deviation
from human intelligence for which there is no expectation that a
person will become smarter only because they study more.

...


* COMMENT Local variables

  Taken from: 
  https://emacs.stackexchange.com/a/76549/11978
  
  # Local Variables:
  # org-md-toplevel-hlevel: 2
  # End:
  


