#+LANGUAGE: en
#+OPTIONS: toc:nil  broken-links:mark

#+begin_export html
---
layout: post.liquid
title:  "AI Career"
date: 2024-10-02
last_updated: 2024-10-02
tags:
  - journal
  - ai
  - job
  - career
  - chollet
  - software
categories: [journal]
permalink: /2024-10-02-ai-career
toc: false
---

#+end_export


After 14 years as a software engineer I decided to
switch roles to work on IT infrastructure and discarded the the idea
to pursue roles for AI projects. 

#+begin_export html
{% include amzn_affiliate_disclaimer.html %}
#+end_export


* Act I

  Working as a software engineer can be stressful. The pace of
  modern/agile software teams is fast, bi-weekly sprints, continuous
  delivery, you build it ... you run it, etc.. On top of that, having
  to learn the next programming tool/technique is very demanding.

  I'm more of a thinker than a tinkerer; I like to look at topic from
  different angles, do some research, try a few experiments, step back
  and switch to something else while I let my brain process what I've
  learned, I might or might not come back to the topic depending on my
  level of interest or curiosity. My working preferences were not
  compatible with my programming job.

  During my vacation around the end of 2021 I was going over my career
  prospects; I thought that I was ready to commit to a role long-term
  but I needed to do some research to understand my options and
  compare them somehow.

  
  
* Act II

  The first half of my career has been writing network clients and
  then writing application servers and release automation for the
  other half. I felt that I had been doing the same over and over only
  with different technologies and industry domains.

  I didn't feel that I could make a drastic change like going out of
  the software scene since writing software was my main activity in
  the past 10 years. I am not a big risk taker so I only considered
  alternative paths that could benefit from my experience as a
  programmer. 

  I had narrowed down my options to two: software architecture and
  artificial intelligence.

  In recent projects, my interest was often to get a glimpse of
  the the high-level architecture and I would approach it by studying
  the delivery pipelines; when available, they describe the process
  each code change goes through to make it to a production
  environment.

  Artificial Intelligence was interesting because it aligns well with
  personal interest in the automation of knowledge organization and
  discovery.
  
  I found two resources that helped me Learn about what AI projects
  might look like in the industry:

  1. Chollet's book:
     @@html:<a href="https://amzn.to/3BsKjwK" target="_blank">
     Deep Learning with Python:</a>@@
     the Universal Machine Learning workflow was exactly what I was
     looking for at the time, a high-level overview of the life cycle
     of an ML Project.

  2. Andrew Ng's content at [[https://www.deeplearning.ai/][deeplearning.ai]]: there I found
     descriptions of the different roles required to execute AI
     projects in the enterprise world. The site also has tools to
     asses your readiness for specific roles.


  I was dissapointed but not very suprised to learn that machine
  learning projects look very similar to other software projects.
  
  AI/ML engineers bring their specialized skills to a project and were
  I to join an AI project, I would end up in a role almost
  indistinguishable to my current role, namely working on the delivery
  of AI-powered software to production environments.
  
  
* Act III

  During my vacation I made the resolution to double down and continue
  working as a software engineer and become even more proficient
  writing code for applications and release automation.
  
  My resolution lasted about 4 hours after my return to work. On my
  first day after vacation, all it took was to read my mailbox and
  chat messages to remind me the many reasons why I was considering a
  change in the first place.

  I started looking for a new role and that lead me into the world of
  IT infrastructure architecture. The company is large and for the
  past 50 years has deployed pretty much every piece of technology
  worth mentioning; my IT universe expanded and I felt quite good
  about not pursing AI/ML.

  If you are considering a career in AI/ML, I highly recommend
  Chollet's book; it's a window into the world of machine learning
  engineering in the industry, directly from a very influential
  software engineer and AI researcher.



* DONE Story structure checklist: [[https://chatgpt.com/share/66fea7f2-cdf4-800f-ada1-cc9b8a748c57][chat]]                             :noexport:
  CLOSED: [2024-10-06 So 21:19]
  :LOGBOOK:
  - CLOSING NOTE [2024-10-06 So 21:19]
  :END:
  
* COMMENT Local variables

  Taken from: 
  https://emacs.stackexchange.com/a/76549/11978
  
  # Local Variables:
  # org-md-toplevel-hlevel: 2
  # End:
  


