#+LANGUAGE: en
#+OPTIONS: toc:nil  broken-links:mark

#+begin_export html
---
layout: post.liquid
title:  "Human intelligence (IQ) is stable"
date: 2024-10-22
last_updated: 2024-10-22
tags:
  - journal
  - intelligence
  - stable
  - iq
  - ai
categories: [journal, ai]
permalink: /2024-10-22-iq-is-stable
toc: false
---

#+end_export

Humans learn new skills all the time but we don't think they are smarter
because of it; why do we consider AI systems smarter when they acquire
new skills?


** Human intelligence on adults is stable over time

   1. adult humans can learn new skills that allow us to solve more
      tasks:

      - even after learning new things, it is expected that
        intelligence will remain stable and not increase in proportion
        to the number of skills/tasks that we have mastered

      - for artificially intelligent systems, it seems that acquiring
        new skills or being able to solve more take effectively
        increases the system's rank in the relevant benchmarks; in a
        way for AI systems it's ok to believe that more skills/tasks
        means higher intelligence

      - intelligence tests for humans and machines are different:

        + IQ and g-factor are measures of an individual's variance in
          performance with respect to a population

        + Typical AI benchmarks typically measure performance on
          specific tasks.


   A notable exception is [[https://pgpbpadilla.github.io/chollet-general-intelligence-test][Chollet's proposed measure for intelligence]],
   which tries to measure skill acquisition efficiency.          

   2. In the ARC challenge, the intelligence of a given system depends
      on the task

      A system may seem more or less intelligent depending on the
      difficulty of the task and on whether the task falls within the
      scope of the system.

      - intuitively this also makes sense for humans, if the task is
        outside of the scope of tasks that we can solve, it may seems
        that we are not very intelligence; conversely if a task is
        very easy it may give the impression that we're very smart if
        we use the level of effort as a proxy for intelligence,
        namely, if the effort required is small it must be cause our
        intellect is large



** TODO What does IQ measure?

   1. IQ operationalize the g-factor


** TODO relationship to g-factor

   The [[https://en.wikipedia.org/wiki/G_factor_(psychometrics)][g-factor]] tries to measure the variance in intelligence amongst
   individuals.

   Intelligence tests measure various domains of intelligence, e.g.,
   visual, logical, verbal, etc.  By measuring distinct aspects of
   intelligence, we can find correlations between them and identify
   the common factor -- the g-factor -- that /connects/ them all.


** TODO IQ and g-factor are an oversimplification

   
** TODO Artificial General Intelligence

   There are two ways that I can interpret the goal of trying to build
   /general/ intelligence:

   1. trying to recreate the kind of intelligence that the g-factor
      tries to measure
   2. trying to recreate the kind of intelligence that can be used to
      solve any kind of problem


   Improving the performance on any of the two interpretations above
   would make our artificial agents capable to solve problems that
   have not seen during training.
   
   
* COMMENT Local variables

  Taken from: 
  https://emacs.stackexchange.com/a/76549/11978
  
  # Local Variables:
  # org-md-toplevel-hlevel: 2
  # End:
  


