#+LANGUAGE: en

#+begin_comment
1) =toc:nil=: Do not generate Org TOC:
   https://orgmode.org/manual/Table-of-Contents.html
2) =broken-links=: Continue export even when there are broken links 
   https://orgmode.org/manual/Export-Settings.html
#+end_comment
#+OPTIONS: toc:nil  broken-links:mark

#+begin_comment
Jekyll front matter:
https://jekyllrb.com/docs/front-matter/
#+end_comment
#+begin_export html
---
layout: post.liquid
title:  "Salsa practice ideas"
date: 2025-05-03
last_updated: 2025-05-03
tags:
  - salsa
  - dancing
categories: [salsa, dancing]
permalink: /2025-05-03-salsa-practice
toc: true
---

#+end_export

Here are some ideas for salsa dance practice, the main goals are to
train the ability to place the pause at different times deliberately. 

During the COVID pandemic I started to get bored of practicing only
the On 1 basic step for inline Salsa. I was trying to come up with
some ideas to spice up my practice sessions and also understand more
about the different ways of dancing inline Salsa.

One of the key concepts in Salsa is the pause. My goal was to
see how placing the pause in different beats changes the feel of
the dance. 


* The Basic step On 1

  For the Basic steps On 1, start by taking a step forward with the
  left foot and stepping with the ball of your foot on beat 1 and the
  pause comes in beats 4 and 8. 
  
  #+begin_export html
  <div style="text-align: center">
    <a href="assets/svg/salsa-on1-basic.svg">
      <img src="assets/svg/salsa-on1-basic-pause-on-4-8.svg"
           alt="On 1 Basic step">
    </a>
  </div>
  #+end_export


** Remarks on symbols
   :PROPERTIES:
   :CUSTOM_ID: symbols
   :END:

   1. *the beat*: the first row shows the beat, in Salsa music there are
      2 sets of 4 beats, 8 in total
   2. *home position*: the beat 0 shows the initial position, some
      people also call this the home position
   3. *transfer of weight*: the red color in the steps indicates where
      your body weight is supposed to be
   4. only the *ball of your feet* touch the ground: the footprints
      without the heel mean that you are only stepping with the ball
      of your feet
   5. *traveling foot*: an arrow instead of a step shows the direction
      your foot is traveling and not touching the ground
   6. *step on the beat*: the X in the last row mean that foot touches
      the ground on that beat
   7. *pause*: the Ps in the last row tell you where the pause is



* Changing the timing of the Pause
  :LOGBOOK:
  - CLOSING NOTE [2025-05-08 Do 23:27]
  :END:

  For reference, in the On 1 Basic, the pause is on beats 4 and 8. The
  goal is now to move the Pause to a different beat. To simplify,
  let's divide the eight beats into 2 sets of 4. This means that
  the Pause is on beat 4 for each set of 4 beats.

  Let's now deliberately pause on a different beat, e.g., 1, 2, or 3.
  
  
** Pause on beats 1 and 5

   #+begin_export html
   <div style="text-align: center">
     <a href="assets/svg/salsa-on1-basic.svg">
       <img src="assets/svg/salsa-on1-basic-pause-on-1-5.svg"
            alt="On 1 Basic step">
     </a>
   </div>
   #+end_export


** Pause on beats 2 and 6

   #+begin_export html
   <div style="text-align: center">
     <a href="assets/svg/salsa-on1-basic.svg">
       <img src="assets/svg/salsa-on1-basic-pause-on-2-6.svg"
            alt="On 1 Basic step">
     </a>
   </div>
   #+end_export


** Pause on beats 3 and 7

   #+begin_export html
   <div style="text-align: center">
     <a href="assets/svg/salsa-on1-basic.svg">
       <img src="assets/svg/salsa-on1-basic-pause-on-3-7.svg"
            alt="On 1 Basic step">
     </a>
   </div>
   #+end_export



* Other ways to change the location of the Pause

  1. you can use the same ideas of placing the pause on different
     beats when dancing On 2
  2. one more way to change the location of the pause is to step on
     the Clave beats


* TODO Dancing on the Clave beats

** TODO Clave 2-3

** TODO Clave 3-2

   
* Conclusion

  Now you have 6 ways to practice placing the pause:
  
  1) 4 positions of the pause on the basic and
  2) 2 positions when dancing on the clave beats (clave 2-3 and 3-2)





* COMMENT Local variables
  
  Taken from: 
  https://emacs.stackexchange.com/a/76549/11978
  
# Local Variables:
# org-md-toplevel-hlevel: 2
# End:
  
