#+LANGUAGE: en

#+begin_comment
1) =toc:nil=: Do not generate Org TOC:
   https://orgmode.org/manual/Table-of-Contents.html
2) =broken-links=: Continue export even when there are broken links 
   https://orgmode.org/manual/Export-Settings.html
#+end_comment
#+OPTIONS: toc:nil  broken-links:mark

#+begin_comment
Jekyll front matter:
https://jekyllrb.com/docs/front-matter/
#+end_comment
#+begin_export html
---
layout: post.liquid
title:  "Salsa practice ideas"
date: 2025-05-03
last_updated: 2025-05-03
tags:
  - salsa
  - dancing
categories: [salsa, dancing]
permalink: /2025-05-03-salsa-practice
toc: true
---

#+end_export

Here are some ideas for salsa dance practice, the main goals are to
train the ability to emphasize the pause at different times, as well
as to vary the sequence of steps and try all combinations. Have fun!


I started learning Salsa back in 2017 while I was living and working
in the Greater Seattle area. The class was taught at the [[https://centuryballroom.com][Century
Ballroom]], there I started my Salsa journey with the Basic step On 1,
LA Style.  


* The Basic step On 1

  For the Basic steps On 1, start by taking a step forward with the
  left foot and stepping with your toe on beat 1 and the pause comes in
  beat 4. Read on for an explanation of the following diagram.

  
  #+begin_export html
  <div style="text-align: center">
    <a href="assets/svg/salsa-on1-basic.svg">
      <img src="assets/svg/salsa-on1-basic.svg"
           alt="On 1 Basic step">
    </a>
  </div>
  #+end_export


** Remarks on symbols
   :PROPERTIES:
   :CUSTOM_ID: symbols
   :END:

   1. the beat: the first row shows the beat, in Salsa music there are
      2 sets of 4 beats, 8 in total
   2. home position: the beat 0 shows the initial position, some
      people also call this the home position
   3. transfer of weight: the red color in the steps indicates where
      your body weight is supposed to be
   4. only toes: the footprints without the heel mean that you are
      only stepping with your toes
   5. traveling foot: an arrow instead of a step shows the direction
      your foot is traveling
   6. step on the beat: the X in the last row mean that you need to
      step on the beat
   7. pause: the Ps in the last row tell you where the pause is
      supposed to be



* TODO Changing the timing of the Pause

  For reference, in the On 1 Basic, the pause is on beats 4 and 8. The
  goal is now to move the Pause to a different beat. To simplify,
  let's divide the eight beats into 2 sets of 4. This means that
  the Pause is on beat 4 for each set of 4 beats.

  Let's now deliberately pause on a different beat, e.g., 1, 2, or 3.
  
  
** TODO Pause on beat 1

** TODO Pause on beat 2

** TODO Pause on beat 3


* TODO Change the Pause while dancing On 2

  The same idea can be used to train the Pause when dancing On 2.


* TODO Stepping on the Clave beats
  

* Takeaways

  1. now you have not only 2 ways to dance (On 1 and On 2); you have 8
     ways to dance by choosing when to pause
  2. you also have 2 additional ways to emphasize the Pause by steping
     stricly on the clave beats, so that's 10 ways to dance already!
  3. when making a Pause, you can do it softly or forcefully; during
     practice anything goes but when dancing with a partner let the
     music tell you if you should use soft long moves or short fast
     ones 



      

* COMMENT Local variables
  
  Taken from: 
  https://emacs.stackexchange.com/a/76549/11978
  
# Local Variables:
# org-md-toplevel-hlevel: 2
# End:
  
